name: Pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          python-version: [ "3.8"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
         python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
    - name: Generar Datos
      run: |
         python 01_generar_datos.py
         ls -l sample.csv
    - name: Ingestar Datos
      run: |
         python 02_ingestar.py
         ls -l train.csv test.csv
    - name: Entrenar 
      run: |
         python 03_entrenar.py
         ls -l mlparams
    - name: Probar
      run: |
         python 04_validar.py
    - name: Aprovisionar
      env:
         AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      run: |
         python 05_aprovisionar.py
    #   env:
    #     AWS_ACCESS_KEY_ID:  ${{secrets.AWS_ACCESS_KEY_ID}}
    #     AWS_ACCESS_KEY_ID:  ${{secrets.AWS_SECRET_ACCESS_KEY}}
    #     ACCOUNT_NUMBER: ${{secrets.ACCOUNT_NUMBER}}
    #     ECR_REPO_NAME: ${{vars.ECR_REPO_NAME}}
    - name: Imagen Contendor
      run: docker build . --file Dockerfile --tag dummyml:latest
      
    